@intern challenge/four/cmp one
Nailujj/FORTA_Coumpound_III_bots pull request #2
Opened 2024-08-16 13:41 UTC by Nailujj

2024-08-19 21:02 UTC, Vxatz requested changes

2024-08-26 14:55 UTC, Nailujj commented on CMP01/src/thresholdCache/thresholdCache.ts
> +};
it calls itself periodically every 24h since that is my time period i set. historical data wont be needed longer than that.

2024-08-26 14:56 UTC, Nailujj commented on CMP01/src/thresholdCache/thresholdCache.ts
> +      totalSupplySum = totalSupplySum.add(bigAmount);
you are right i am adjusting

2024-08-28 08:08 UTC, Vxatz requested changes

2024-08-28 08:08 UTC, Vxatz commented on CMP01/src/thresholdCache/thresholdCache.ts
> +});
I'm not sure if there's any difference between `amountCache.amount` and `userSupplyTracker.totalSupplySum` or one could be removed

2024-08-28 08:08 UTC, Vxatz commented on CMP01/src/thresholdCache/thresholdCache.ts
> +export const clearCachePeriodically = () => {
This function is still defined but not invoked anywhere in the code. It can be invoked below L6 in `agent.ts`

2024-09-03 07:44 UTC, merged